<?php

namespace OC\FOSUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FOSUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FOSUserRepository extends EntityRepository
{
}
