ocfos_user:
    resource: "@OCFOSUserBundle/Resources/config/routing.yml"
    prefix:   /

oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /

main_core:
    resource: "@MainCoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_planning:
    resource: "@OCPlanningBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
