parameters:
#    ocfos_user.example.class: OC\FOSUserBundle\Example

services:
#    ocfos_user.example:
#        class: %ocfos_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
