# src/OC/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }
    


oc_platform_home:
    path:      /platform
    defaults:  { _controller: OCPlatformBundle:Advert:index }
    
oc_platform_view:
    path:      /platform/advert/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:view }
    
oc_platform_add:
    path:      /platform/add
    defaults:  { _controller: OCPlatformBundle:Advert:add }
    
oc_platform_view_slug:
    path:      /platform/{year}/{slug}.{format}
    defaults:  { _controller: OCPlatformBundle:Advert:viewSlug, format: html }
    requirements:
       year:   \d{4}
       # format: html|xml

oc_platform_view_month:
    path:      /platform/{year}/{month}/{day}
    defaults:  { _controller: OCPlatformBundle:Advert:viewMonth }
    requirements:
       year:   \d{4}
       month:  \d{2}
       day:    \d{2}
       # format: html|xml
       
oc_platform_home:
    path:      /{page}
    defaults:  { _controller: OCPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*
        
#oc_platform_view:
 #   path:      /advert/{id}
 #   defaults:  { _controller: OCPlatformBundle:Advert:view }
 #   requirements:
 #       id: \d+
        
oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:add }
oc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id: \d+
oc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+