parameters:
#    main_core.example.class: Main\CoreBundle\Example

services:
#    main_core.example:
#        class: %main_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    main_core.antispam:
        class: Main\CoreBundle\Antispam\MainAntispam
        arguments: [@mailer, %locale%, 50]
        tags:
            -  { name: twig.extension }
    
    main_core.menu_builder:
        class: Main\CoreBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]
        
    main_core.menu.main:
        class: KnpMenuMenuItem
        factory_service: main_core.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main } #alias main